### ISSUE TITLE
ahbot tables missing from characters database

### ISSUE THREAD

**Issue by majathom68** [LordPsyan/LordPsyanBots#1]
First of all great work on this.  Have had no issues compiling or running apart from the core auction house bot and the playerbot.  But all good things take time.

Anyway Im not a fan of problems just solutions so the characters database is missing the 3 following tables ahbot_history, ahbot_category and ahbot_price.  I found this when turning on the ahbot.enabled flag in the ahbot.conf.  So your characters_database.sql is missing:

DROP TABLE IF EXISTS `ahbot_history`;
DROP TABLE IF EXISTS `ahbot_category`;
DROP TABLE IF EXISTS `ahbot_price`;

CREATE TABLE `ahbot_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `buytime` bigint(20) NOT NULL,
  `item` bigint(20) NOT NULL,
  `bid` bigint(20) NOT NULL,
  `buyout` bigint(20) NOT NULL,
  `won` bigint(20) NOT NULL,
  `category` varchar(45) DEFAULT NULL,
  `auction_house` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `won` (`won`),
  KEY `category` (`category`),
  KEY `auction_house` (`auction_house`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ahbot_category` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `category` varchar(45) DEFAULT NULL,
  `multiplier` decimal(20, 2) NOT NULL,
  `max_auction_count` bigint(20) NOT NULL,
  `expire_time` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `helper` (`category`, `multiplier`, `expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ahbot_price` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `item` varchar(45) DEFAULT NULL,
  `price` decimal(20, 2) NOT NULL,
  `auction_house` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ahbot_price_item` (`item`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
So I'm also a programmer and have been mucking around with the Trinity core but have been highly interested in playerbots and have looks into ike3 earlier work.  But came across yours, been more up to date and using the latest TC core has me now hooked so if there is anything I can possibly help with drop me line.

**Comment by Talmeron** [comment]
Ike3's AHBot should stay disabled as it makes it pretty much unusable right now.

**Comment by LordPsyan** [comment]
not sure how I missed that. Putting that sql into both characters_database.sql and characters-R01-R02.sql files. will push shortly. Thanks for letting me know.

**Comment by LordPsyan** [comment]
all fixed. Thanks again for letting me know I forgot this.
