### ISSUE TITLE
Compiling fails on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by iMontouch** [LordPsyan/LordPsyanBots#10]
The make process fails at 99% with this error:
`../../plugins/libplugins.a(CustomStrategy.cpp.o): In function `ai::CustomStrategy::InitTriggers(std::list<ai::TriggerNode*, std::allocator<ai::TriggerNode*> >&)':
CustomStrategy.cpp:(.text+0xba0): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
CustomStrategy.cpp:(.text+0xbb9): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
CustomStrategy.cpp:(.text+0xbce): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
CustomStrategy.cpp:(.text+0xbf7): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator*()'
CustomStrategy.cpp:(.text+0xd3e): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/server/worldserver/worldserver] Error 1
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [all] Error 2
`
Any more information you will need?

**Comment by LordPsyan** [comment]
Which branch?

**Comment by LordPsyan** [comment]
This error is due to an outdated gcc or g++. Ubuntu 14.04.03 contains gcc version 4.8.4 and you need at least version 4.9. Do this to update your g++:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.9
```

**Comment by LordPsyan** [comment]
I just tested this, and it compiled properly. No more regex errors.

**Comment by LordPsyan** [comment]
This error is due to an outdated gcc or g++. Ubuntu 14.04.03 contains gcc
version 4.8.4 and you need at least version 4.9. Do this to update your g++:

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.9 gcc-4.9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9
60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

**Comment by elifkus** [comment]
I had the same error on Centos 7. But the latest version of gcc is 4.8.5  on Centos 7. To workaround this issue I used devtoolset-3
http://linux.web.cern.ch/linux/centos7/docs/softwarecollections.shtml#inst

```
yum install centos-release-scl
yum install devtoolset-3-gcc-c++
```

After that 

`scl enable devtoolset-3 bash `

This enables gcc/g++ v4.9 in the current terminal session only.
