### ISSUE TITLE
TrinityAHbot will not load items into AH

### ISSUE THREAD

**Issue by Grimmy347** [LordPsyan/LordPsyanBots#15]
**Description**:
I do not desire to use the new ahbot and rather use trinity ahbot but it will not load items into auction house.  everything looks like it is working in console but nothing is actually loading to auctionhouse db.
**Current behaviour**: Tell us what happens
if I do ahbot status all it shows diff quality items in the total amount line but nothing in the alliance/n/horde lines
**Expected behaviour**: Tell us what should happen instead
items load into other auction houses
**Steps to reproduce the problem**:

1.downloaded lordpsyanbots
2.compliled and setup configs
3.applied database patches

**Branch(es)**: 335

**TC hash/commit**:

**TDB version**:

**Operating system**:
windows 10

**Comment by iliveforgod347** [comment]
to be clear, i would like to use trinity ah bot rather than the ike3 ah bot.  I just tried to build a server based on the patches branch and I still could not get the trinity AH to actually populate with anything.

**Comment by iliveforgod347** [comment]
Is there a way I can just hard code remove ike3 AH mod?  How would I go about doing that so I can get the regular one to work?

**Comment by keeloi79** [comment]
I am having the same issue. Also the Ike AHBot when it works only fills ~300 items no matter what settings are placed for max items in the config.

**Comment by iliveforgod347** [comment]
I actually figured out how to fix this:


"Looks like I found the problem:

    /// <li> Handle AHBot operations
    if (m_timers[WUPDATE_AHBOT].Passed())
    {
        sAuctionBot->Update();
        m_timers[WUPDATE_AHBOT].Reset();
    }

The timer in the world.cpp was commented out so I uncommented it and it now works like a charm."

**Comment by iliveforgod347** [comment]
I posted this on his bit bucket site.

**Comment by keeloi79** [comment]
Going to try and recompile and see if it works. I should have mentioned I am compiling and running the server on Linux. That shouldn't make a difference though.

**Comment by keeloi79** [comment]
Update: Compiled for Linux and worked swimmingly. AHBot commands now function as they're designed to: status, rebuild, etc.

**Comment by iliveforgod347** [comment]
Good to hear.  I knew very little about most involved in trinity but by the time I figured out how to fix this, I learned quite a bit.  Not sure why it was commented out in the first place though.

**Comment by keeloi79** [comment]
Dunno, I am new to it myself. I messaged around with the original Mangos in 2005-2006 so coming back to it all now it is amazing how much everything has evolved. Luckily I've got a decent server (dual cpu, 16 cores, 32 threads) to work on; it takes less than 10 minutes to compile and make the linux executables (make -j 28 && make install). Makes it tons easier to test changes/edits to the source code.

**Comment by iliveforgod347** [comment]
Do you run linix on your main computer?  I use windows and am finding it to cause some compile errors.  Not sure if I want to dive into the world of Linux just to get things working for this.

**Comment by keeloi79** [comment]
Yes I have it running on Linux. Specifically Ubuntu 15.04. It is now
working great.

**Comment by LordPsyan** [comment]
I know I havent worked on this in forever. I am adding the world.cpp fix, thanks to Grimmy347, and I am adding most of my other patches to it. I will slowly update this to more recent revisions of TC. This will be a long slow process, but you can find all the patch descriptions on my bitbucket repo. I will attempt to list all patches I am adding to this repo. Thanks again for the fix. Not sure why that was commented out.
