### ISSUE TITLE
Cant run worldserver

### ISSUE THREAD

**Issue by JohnvanWaYnE** [LordPsyan/LordPsyanBots#17]
**Description**:
Worldserver wont Update/start with the following Message:

>> Reapplying update "2016_03_04_99_world.sql" 'CAAE708' -> 
'0A94B23' (it changed)...  ERROR 1136 (21S01) at line 60: Column count doesn't match value count at row 1 

Applying of file '/home/wow/LordPsyanBots/sql/updates/world/2016_03_04_99_world.sql' to database 'world' failed! If you are an user pull the latest revision from the repository. If you are a developer fix your sql query.
Could not update the World database, see log for details.

**Current behaviour**: Tell us what happens
I compiles the Source and configured all and then this happens
**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 335/6x
335
**TC hash/commit**:

**TDB version**:
TDB 335.63
**Operating system**:
Debian-Linux

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by LordPsyan** [comment]
Today I will update the LordPsyanBotsDB repo. This will be a basic install database, with all updates. It will take me time, as I just got a new server and I am still setting everything up.

**Comment by scroftster** [comment]
i was trying also. Thanks for looking into a fix.
