### ISSUE TITLE
new repo empty response

### ISSUE THREAD

**Issue by Wyntau** [LordPsyan/LordPsyanBots#19]
http://git.realmsofwarcraft.com/lordpsyan/LordPsyanBots can't be accessed. Does the website is a private website or blocked my IP?

chrome said: ERR_EMPTY_RESPONSE

@LordPsyan

**Comment by Astraithious** [comment]
Also curious where it is now @LordPsyan

**Comment by olivernybroe** [comment]
Same is happening for me.

**Comment by LordPsyan** [comment]
changed to http://git.lordpsyan.com
