### ISSUE TITLE
TC Core auction house not running fix

### ISSUE THREAD

**Issue by majathom68** [LordPsyan/LordPsyanBots#2]
By design of the playerbot modifcations.  The default TC auction house is disabled in the game\world.cpp by being commented out.  I located the following code and uncommented it:

  /// <li> Handle AHBot operations
     if (m_timers[WUPDATE_AHBOT].Passed())
    {
        sAuctionBot->Update();
        m_timers[WUPDATE_AHBOT].Reset();
    }
    // end of playerbot mod

its around line 2150.

Once recompiled and started the auction house database is now populated

**Comment by LordPsyan** [comment]
I will fix it so if ike3 ahbot is disabled, it leaves that line enabled. too early in the morning to write an explanation any clearer than what I wrote... need coffee...

**Comment by LordPsyan** [comment]
Not yet tested, but I added a line in worldserver.conf that, by default, is set to 0. This line should be set to 1 if using ike3's ahbot. will probably cause serious issues if its set to 0 with ike3's ahbot enabled.

Let me know if this fixes the issue

**Comment by LordPsyan** [comment]
it all seems to be fixed now. closing issue
