### ISSUE TITLE
No random bots joining and segfault after .bot add command

### ISSUE THREAD

**Issue by monsune** [LordPsyan/LordPsyanBots#3]
We compiled and tested newest without problems on windows. Accounts and chars created, random bots joining nicely, .bot commands working fine. We tried the same on linux and we were able to compile just fine. On startup accounts and chars were created but not a single bot has joined. Also issuing the command .bot add causes an instant crash. We can't find a single entry in server.log related to this.

If there is any extra info that you may need or if anyone else can confirm working/non-working build on linux please let us know. We are working hard to solve this issue but we aren't sure if this is our fault somewhere or an extreme bug.

So far we run on debug and the last thing seen in logs is: Account: 52 (IP: ) Login Character:[Buns] (GUID: 904) Level: 1. After that segfault. The actual .bot add command seems to be working as lots of stuff is being processed like character stats and data loaded, etc. For some odd reason it crashes on character login though.

We tried to recompile, also redid databases from scratch. Nothing helps. And just on linux as it works fine on windows (besides bugs like sometimes a bot stops responding to commands and needs to be removed and added again - this is going to be issued in another ticket soon).

**Comment by LordPsyan** [comment]
Need to know what version of linux you are using. I had this issue on debian 7 x64 but not on any other Linux version.

**Comment by Talmeron** [comment]
I think this can close since it's been addressed on the bitbucket repo.

**Comment by LordPsyan** [comment]
Yes, this can close. Still bugs with ike3 bots, and instead of making things easier, I made it harder by including new NPCBots with ike3. Most issues that cause crashes have been fixed.
