### ISSUE TITLE
Lunux Process stop

### ISSUE THREAD

**Issue by sesserg** [LordPsyan/LordPsyanBots#4]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
x86_64

![error](https://cloud.githubusercontent.com/assets/3738506/10966669/26aefdb0-83c6-11e5-8682-18abdf8d2cbf.png)

All Ahbot - disabled, mmaps - disabled.
Is any Idea?
IF Palyerbot - disable - all OK.

**Comment by LordPsyan** [comment]
This one took me forever to figure out. There was a string that was a null value, but a string can't be null. it can be empty, but null is apparently reserved for char or int, etc. I fixed it, but can't remember how... lol
