### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sout12** [LordPsyan/LordPsyanBots#5]
How do i install, i got a trintiycore?

**Comment by LordPsyan** [comment]
This includes trinitycore. you install it the same way as you would trinitycore source. You can check out TrinityCore wiki at http://www.trinitycore.info for more information on installing. I try to keep this repo as up-to-date with trinitycore as possible.

If you are looking for a stand alone patch to add to your trinitycore source, try https://bitbucket.org/lordpsyan/trinitycore-patches/
