### ISSUE TITLE
complered :error C4263

### ISSUE THREAD

**Issue by yabiange** [LordPsyan/LordPsyanBots#9]
When I completed the code, It gave me this error:
\Wow\Core\LordPsyanBots\src\server\game\AI\NpcBots\bot_ai.h(393): error C4263: “void bot_ai::EnterEvadeMode(void)”: 成员函数不重写任何基类虚拟成员函数 (H:\Wow\Core\LordPsyanBots\src\server\scripts\Commands\cs_npc.cpp)

my system: vs2013 whit update4
win10 pro
boost_1_60_0-msvc-12.0-64
 can you fix it?

**Comment by LordPsyan** [comment]
I wish I could fix this, but I have yet to figure out why windows is throwing this error. It is saying the function is hidden, but it is not hidden. There were some changes made to TC, but I do not see how this causes these errors. It works perfectly fine without errors in linux. It is a windows thing. I will fix it as soon as I understand what is causing this.

**Comment by yabiange** [comment]
I hope you can fix it. I can't wait for play your core as soon as possble.
Thank you anyway.

**Comment by LordPsyan** [comment]
I removed new npcbots from lordpsyanbots. If you are running linux, you can add it manually using the patch from bitbucket.
